language: python

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

# safelist
branches:
  only:
    - develop
    - main

install:
  - pip install tchappui-webdrivers
  - pip install -r requirements.txt


before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux32.tar.gz
  - tar -xzf geckodriver-v0.30.0-linux32.tar.gz
  - sudo cp geckodriver /usr/bin


env:
  global:
    - DJANGO_SETTINGS_MODULE='nutella_fans.settings.test'
    - SECRET_KEY_TRAVIS='travis99secre99tkey'
    - DB_NAME='openfoodfact_db'
    - DB_USER='postgres'
    - DB_PASSWORD='nutellaFans'
    - DB_HOST='localhost'

services:
  - postgresql

script:
  - python3 manage.py test

