language: python

addons:
  # ajouter uniquement les navigateurs utilisés
  firefox: latest

install:
  - pip install tchappui-webdrivers
  - pip install -r requirements.txt
  - install-webdrivers --path webdrivers

before_script:
  - install-webdrivers --path /usr/local/bin/


env:
  global:
    DJANGO_SETTINGS_MODULE=nutella_fans.settings.test
    SECRET_KEY=travis99secre99tkey

services:
  - postgresql

script:
  - python3 manage.py test nutella_fans
