language: python

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

install:
  - pip install tchappui-webdrivers
  - pip install -r requirements.txt


before_script:
  - install-webdrivers --path webdrivers


env:
  global:
    - DJANGO_SETTINGS_MODULE='nutella_fans.settings.test'
    - SECRET_KEY='travis99secre99tkey'

services:
  - postgresql

script:
  - python3 manage.py test


